amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: base_link
    beam_skip_distance: 0.2
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    global_frame_id: map
    laser_likelihood_max_dist: 2.0
    laser_model_type: likelihood_field
    max_particles: 800
    min_particles: 300
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: differential
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.5
    update_min_a: 0.2
    update_min_d: 0.25

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "package://nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml"
    plugin_lib_names: ["nav2_bt_navigator/plugins/navigate_to_pose_action_bt_node", "nav2_bt_navigator/plugins/change_goal_action_bt_node", "nav2_bt_navigator/plugins/follow_path_action_bt_node"]

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 15.0
    min_x_velocity_threshold: 0.05
    min_y_velocity_threshold: 0.05
    min_theta_velocity_threshold: 0.05
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.8
      max_angular_accel: 1.0
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.2
      rotate_to_heading_angular_vel: 1.0
      use_vel_saturation: true
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 10.0
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner/ThetaStar"
      how_many_corners: 72
      max_iterations: 20000
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      tolerance: 1e-2
      max_its: 10
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["spin", "backup", "drive_on_heading"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    plugin_lib_names: ["nav2_waypoint_follower::FollowWaypoints"]
    goal_goldilocks_distance: 0.5

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true
      width: 8.0
      height: 8.0
      resolution: 0.05
      footprint: [[0.25, 0.2], [-0.25, 0.2], [-0.25, -0.2], [0.25, -0.2]]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: lidar
        lidar:
          topic: scan
          data_type: LaserScan
          clearing: true
          marking: true
          inf_is_valid: false
          raytrace_range: 12.0
          obstacle_range: 10.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.45

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: true
      update_frequency: 2.0
      publish_frequency: 2.0
      rolling_window: false
      width: 40.0
      height: 40.0
      resolution: 0.1
      footprint: [[0.25, 0.2], [-0.25, 0.2], [-0.25, -0.2], [0.25, -0.2]]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: lidar
        lidar:
          topic: scan
          data_type: LaserScan
          clearing: true
          marking: true
          inf_is_valid: false
          raytrace_range: 12.0
          obstacle_range: 10.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    max_velocity: [0.7, 0.0, 1.0]
    min_velocity: [0.0, 0.0, -1.0]
    max_accel: [0.7, 0.0, 1.0]
    max_decel: [-0.7, 0.0, -1.0]
